### ISSUE TITLE
Themes are outdated

### ISSUE THREAD

**Issue by brainopia** [chriseppstein/compass-colors#1]
After following commit http://github.com/chriseppstein/compass-colors/commit/6142c97a78ad58eb29868339859fe2356eb59aeb, themes need to be updated so every call to darken/lighten is replaced by darken_percent/lighten_percent.

**Comment by rmm5t** [comment]
This bit me after I upgraded compass-colors ... until I realized what was going on.

Here's a branch that fixes this.  Please pull it.
http://github.com/rmm5t/compass-colors/tree/percentage_in_themes/

Diff:
http://github.com/rmm5t/compass-colors/compare/percentage_in_themes/

**Comment by chriseppstein** [comment]
fixed.
