### ISSUE TITLE
Could not find gem

### ISSUE THREAD

**Issue by joel** [chriseppstein/compass-colors#4]
When add this line to **Gemfile**:

gem 'chriseppstein-compass-colors'
or
gem 'chriseppstein-compass-colors', :git => "git://github.com/chriseppstein/compass-colors.git"

And launch "bundle install" i have this issue :
Could not find gem 'chriseppstein-compass-colors (>= 0)' in any of the gem sources listed in your Gemfile.
or
Could not find gem 'chriseppstein-compass-colors (>= 0)' in git://github.com/chriseppstein/compass-colors.git (at master).
Source does not contain any versions of 'chriseppstein-compass-colors (>= 0)'

**Comment by jeroenvandijk** [comment]
I'm not sure if this gem is still relevant. Color manipulation is in the Sass core now: http://nex-3.com/posts/89-powerful-color-manipulation-with-sass

If you do want to use this gem put the following in your gemfile:

```
 gem 'compass-colors', :git => "git://github.com/chriseppstein/compass-colors.git"
```

And the following in your config.rb

```
 require 'compass-colors'
```

Hope this helps.

**Comment by joel** [comment]
Ok thank you for info
